// This file was automatically generated by autogen-pch.sh

#ifndef STDAFX_H_INCLUDED
#define STDAFX_H_INCLUDED

#ifdef __cplusplus

#include <algorithm>
#include <array>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <type_traits>
#include <utility>

#endif // __cplusplus

#endif // STDAFX_H_INCLUDED
